### ISSUE TITLE
No such file or directory: './KIBA/drugs.csv'

### ISSUE THREAD

**Issue by wpy297** [KEAML-JLU/MSI-DTI#1]
在运行smiles.py时出现了一个bug，想请教一下作者大大，感谢！
## bug详情：
``` 
python smiles.py
No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
2024-06-17 17:28:46.714048: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-17 17:28:48.940267: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with transformers dependency. No module named 'transformers'
cannot import name 'HuggingFaceModel' from 'deepchem.models.torch_models' (/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'jax'
>>> Reading the data file ...
Traceback (most recent call last):
  File "smiles.py", line 44, in <module>
    mol = pd.read_csv(input_file)
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/wupeiyuan/anaconda3/envs/MSI-DTI1/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './KIBA/drugs.csv'
```
## 解压
然后我这里写了一个aaa.py用于解压kiba.npz, aaa.py的内容如下：
```python
import numpy as np
import pandas as pd
import os

# 定义 npz 文件和输出目录
npz_file_path = './KIBA/kiba.npz'
output_folder = './KIBA/'

# 确保输出目录存在
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# 加载 npz 文件，并允许使用pickle
npz_file = np.load(npz_file_path, allow_pickle=True)

# 检查 npz 文件包含的内容
print("Files in the npz archive:")
for file in npz_file.files:
    print(file)

# 提取并保存 npz 文件中的每个文件
for file in npz_file.files:
    data = npz_file[file]

    # 检查是否是字典
    if isinstance(data, dict):
        for key, value in data.items():
            # 假设 value 是一个二维数组，其中第一行是列名
            if isinstance(value, np.ndarray) and len(value.shape) == 2 and value.shape[0] > 1:
                columns = value[0]  # 第一行作为列名
                data_array = value[1:]  # 其余行作为数据
                # 创建 DataFrame
                df = pd.DataFrame(data_array, columns=columns)
                # 保存为 CSV 文件
                output_csv_path = os.path.join(output_folder, f'{key}.csv')
                df.to_csv(output_csv_path, index=False)
                print(f"{key}.csv has been extracted and saved to {output_csv_path}")
            else:
                # 如果不是二维数组或者没有列名，直接保存为 .npy 文件
                output_npy_path = os.path.join(output_folder, f'{key}.npy')
                np.save(output_npy_path, value)
                print(f"{key}.npy has been extracted and saved to {output_npy_path}")
    else:
        # 如果数据不是字典
        output_npy_path = os.path.join(output_folder, f'{file}.npy')
        np.save(output_npy_path, data)
        print(f"{file}.npy has been extracted and saved to {output_npy_path}")

# 检查其中的drugs.csv文件
drugs_csv_path = os.path.join(output_folder, 'drugs.csv')
if os.path.exists(drugs_csv_path):
    print("CSV file content:")
    drugs_df = pd.read_csv(drugs_csv_path)
    print(drugs_df.head())
else:
    print("drugs.csv not found.")


```

运行结果如下：
```
python aaa.py
Files in the npz archive:
dict
dict.npy has been extracted and saved to ./KIBA/dict.npy
drugs.csv not found.
```

是要把dict.npy文件转为csv文件然后再命名成drugs.csv吗？

**Comment by qinchi1** [comment]
我的想法是将dict.npy转化成csv,但是显示：这个错误信息 “ValueError: Must pass 2-d input. shape=()” 表示你正在尝试使用一个函数或方法，这个函数或方法期望接收一个二维输入（通常是矩阵或类似的结构），但是你传入的参数实际上是一个空元组或者没有正确形状的数据。希望了解您是怎么解决的，谢谢
